### ISSUE TITLE
[BUG] 방 배치정보 오류

### ISSUE THREAD

**Issue by 5onchangwoo** [mtvs-6man/roomus-application-server#46]
**버그 설명**
방 배치 정보 idx가 가구의 id가 아닌 시퀀스가 값이 옴

**재현 방법**
1. 방 가구 배치 정보 저장 ( /rooms//{id}/furniture )
2. 방 상세 조회 ( /rooms/{id} )

**예상 응답**
idx 값이 가구의 no가 아닌 가구 정보의 id가 출력

**Comment by mungjin4966** [comment]
확인했습니다.
